export const serverUrl = process.env.NEXT_PUBLIC_SERVER_URL!;

// export all routes generated by nextjs
export type AppRoutes =
    | ""
    | "/"
    | `/?${string}`
    | "/auth"
    | "/payment"
    | `/product/${string}`;

export * from "./comment";
export * from "./coupon";
export * from "./order";
export * from "./payment";
export * from "./product";
export * from "./shipment";
