export { default as CategoriesList } from "./CategoriesList";
export { default as CouponsList } from "./CouponsList";
export { default as EditProduct } from "./EditProduct";
export { default as Index } from "./Index";
export { default as NewCategory } from "./NewCategory";
export { default as NewCoupon } from "./NewCoupon";
export { default as NewProduct } from "./NewProduct";
export { default as OrdersList } from "./OrdersList";
export { default as ProductsList } from "./ProductsList";
